version: "3"

networks:
  dockerapi-dev:
    driver: bridge 

services:
    postgres_image:
      image: postgres:latest
      restart: always
      ports:
        - "5432"
      environment:
        POSTGRES_USER: "test"
        POSTGRES_PASSWORD: "test"
      networks:
        - dockerapi-dev  

    api:
      build:
        context: .
        dockerfile: src/Web/Dockerfile
      depends_on:
        - "postgres_image"
      ports:
        - "127.0.0.1:5000:5000/tcp"
      environment:
        - ASPNETCORE_URLS=http://+:5000
      networks:
        - dockerapi-dev